# Generated by Django 3.2.22 on 2023-11-02 13:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_alter_treenode_name_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_node', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stone_related', related_query_name='stones', to='content.treenode')),
            ],
            options={
                'verbose_name': 'Stein',
                'verbose_name_plural': 'Steine',
            },
        ),
    ]
