# Generated by Django 3.2.22 on 2023-11-02 13:59

from django.db import migrations, models
import django.db.models.deletion
import solid_backend.utils.drf_spectacular_extensions
import stone_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Gesteinsname')),
                ('alt_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternativname')),
                ('eng_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Englischer Name')),
                ('dunham_class', stone_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Mudstone'), ('2', 'Wackestone'), ('3', 'Packstone'), ('4', 'Grainstone'), ('5', 'Floatstone'), ('6', 'Rudstone'), ('7', 'Bafflestone'), ('8', 'Bidnstone'), ('9', 'Framstone')], max_length=1), blank=True, null=True, size=None, verbose_name='Dunhamn Klassifikation')),
                ('add_class', stone_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'fluviatil'), ('2', 'flachmarin'), ('3', 'limnisch'), ('4', 'marin'), ('5', 'kontinentalnah'), ('6', 'glazigen'), ('7', 'glazifuviatil'), ('8', 'gravitativ'), ('9', 'sedimentär'), ('10', 'äolisch'), ('11', 'konkretionär'), ('12', 'kalkig'), ('13', 'kieselig'), ('14', 'oranogen'), ('15', 'karbonatisch'), ('16', 'mergelig'), ('17', 'halogenidisch (Salz)'), ('18', 'sulfatisch'), ('19', 'mafisch'), ('20', 'intermediär'), ('21', 'felsisch')], max_length=2), blank=True, null=True, size=None, verbose_name='Zusatz Klassifikation')),
                ('comment', solid_backend.utils.drf_spectacular_extensions.MDTextField(blank=True, max_length=512, null=True)),
                ('stone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_information', to='stone_content.stone', verbose_name='Stein')),
            ],
            options={
                'verbose_name': 'Allgemein',
                'verbose_name_plural': 'Allgemein',
            },
        ),
    ]
