# Generated by Django 3.2.22 on 2023-11-02 14:19

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import stone_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_content', '0002_generalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sed_fabtric', stone_content.models.ChoiceArrayField(base_field=models.CharField(choices=[('1', 'homogen'), ('2', 'inhomogen'), ('3', 'matrixgestützt'), ('4', 'komponentengestützt'), ('5', 'hohe Rauigkeit'), ('6', 'mittlere Rauigkeit'), ('7', 'geringe Rauigkeit'), ('8', 'sehr geringe Rauigkeit'), ('9', 'gute Sortierung'), ('10', 'mittlere Sortierung'), ('11', 'schlechte Sortierung'), ('12', 'unreif'), ('13', 'mittelreif'), ('14', 'reif'), ('15', 'hochreif'), ('16', 'feine Schichtung'), ('17', 'mittlere Schichtung'), ('18', 'grobe Schichtung'), ('19', 'undeutliche Schichtung'), ('20', 'keine Schichtung'), ('21', 'Schrägschichtung'), ('22', 'Kreuzschichtung'), ('23', 'Rippelschichtung'), ('24', 'mit Hohlräumen'), ('25', 'mit Poren'), ('26', 'Lockergestein'), ('27', 'Festgestein')], max_length=2), size=None, verbose_name='Gefüge (Sediment)')),
                ('ign_fabric', stone_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'gleichkörnig (Mosaikgefüge)'), ('2', 'ungleichkörnig (porphyrisch)'), ('3', 'aphyrisch'), ('4', 'isotrop (ungerichtet)'), ('5', 'leichtes Fließgefüge'), ('6', 'leichte Einregelung'), ('7', 'geringe Rauigkeit'), ('8', 'sehr geringe Rauigkeit'), ('9', 'gute Sortierung'), ('10', 'mittlere Sortierung'), ('11', 'schlechte Sortierung'), ('12', 'unreif'), ('13', 'mittelreif'), ('14', 'reif'), ('15', 'hochreif'), ('16', 'feine Schichtung'), ('17', 'mittlere Schichtung'), ('18', 'grobe Schichtung'), ('19', 'undeutliche Schichtung'), ('20', 'keine Schichtung'), ('21', 'Schrägschichtung'), ('22', 'Kreuzschichtung'), ('23', 'Rippelschichtung'), ('24', 'mit Hohlräumen'), ('25', 'mit Poren'), ('26', 'Lockergestein'), ('27', 'Festgestein')], max_length=2), blank=True, null=True, size=None, verbose_name='Gefüge (Magmatit)')),
                ('meta_fabric', stone_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'porphyroblastisch'), ('2', 'nematoblastisch'), ('3', 'kataklastisch'), ('4', 'mylonitisch'), ('5', 'gleichkörnig'), ('6', 'holokristallin'), ('7', 'massig (ungerichtet)'), ('8', 'ungeregelt'), ('9', 'schiefrig'), ('10', 'gneisig')], max_length=2), blank=True, null=True, size=None, verbose_name='Gefüge (Metamorphit)')),
                ('fabric_comment', models.TextField(blank=True, max_length=256, null=True, verbose_name='Gefüge Anmerkung')),
                ('grain_size', models.CharField(blank=True, max_length=256, null=True, verbose_name='Korngröße')),
                ('color_index', models.CharField(blank=True, max_length=256, null=True, verbose_name="Farbzahl M'")),
                ('color', models.CharField(blank=True, max_length=256, null=True, verbose_name='Farbe')),
                ('density', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True, verbose_name='Dichte [g/cm³]')),
                ('porosity', models.CharField(blank=True, choices=[('1', 'keine'), ('2', 'sehr gering'), ('3', 'gering'), ('4', 'mittel'), ('5', 'hoch'), ('6', 'sehr hoch')], max_length=11, null=True)),
                ('stone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='stone_content.stone', verbose_name='Stein')),
            ],
            options={
                'verbose_name': 'Eigenschaften',
                'verbose_name_plural': 'Eigenschaften',
            },
        ),
    ]
