# Generated by Django 3.2.22 on 2023-11-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0021_alter_generalinformation_chemical_formula'),
        ('stone_content', '0003_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compounds', models.CharField(blank=True, help_text="Nur Mineralbestandteile eingeben, die nicht in 'Mineralien im Bestand' ausgewählt sind. Eingabeformat: Varietät1, Varietät2, ...", max_length=256, null=True, verbose_name='Mineralbestandteile')),
                ('crystal_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kristallanteil in %')),
                ('components', models.CharField(blank=True, max_length=256, null=True, verbose_name='Komponenten')),
                ('matrix', models.CharField(blank=True, max_length=256, null=True, verbose_name='Matrix')),
                ('cementation', models.CharField(blank=True, choices=[('1', 'kalkig'), ('2', 'kieselig')], max_length=1, null=True)),
                ('mineraltype_compounds', models.ManyToManyField(blank=True, null=True, to='geomat_content.MineralType', verbose_name='Mineralien im Bestand')),
                ('stone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='stone_content.stone', verbose_name='Stein')),
            ],
            options={
                'verbose_name': 'Zusammensetzung',
                'verbose_name_plural': 'Zusammensetzungen',
            },
        ),
    ]
