# Generated by Django 3.2.22 on 2023-11-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stone_content', '0004_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent', models.TextField(blank=True, max_length=512, null=True, verbose_name='Edukt')),
                ('formation', models.TextField(blank=True, max_length=512, null=True, verbose_name='Bildung')),
                ('locality', models.CharField(blank=True, max_length=256, null=True, verbose_name='Lokalität')),
                ('age', models.CharField(blank=True, max_length=256, null=True, verbose_name='Alter')),
                ('stone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergence', to='stone_content.stone', verbose_name='Stein')),
            ],
            options={
                'verbose_name': 'Entstehung & Vorkommen',
                'verbose_name_plural': 'Entstehungen und &Vorkommen',
            },
        ),
    ]
