# Generated by Django 3.2.22 on 2024-01-11 10:30

from django.db import migrations, models
import stone_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_content', '0006_rename_alt_name_generalinformation_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='porosity',
            field=models.CharField(blank=True, choices=[('1', 'keine'), ('2', 'sehr gering'), ('3', 'gering'), ('4', 'mittel'), ('5', 'hoch'), ('6', 'sehr hoch')], max_length=11, null=True, verbose_name='Porosität'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='dunham_class',
            field=stone_content.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Mudstone'), ('2', 'Wackestone'), ('3', 'Packstone'), ('4', 'Grainstone'), ('5', 'Floatstone'), ('6', 'Rudstone'), ('7', 'Bafflestone'), ('8', 'Bidnstone'), ('9', 'Framstone')], max_length=1), blank=True, null=True, size=None, verbose_name='Dunham Klassifikation'),
        ),
    ]
