# Generated by Django 3.2.22 on 2024-01-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stone_content', '0008_alter_composition_cementation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='sub_name',
            new_name='alt_name',
        ),
    ]
