# Generated by Django 3.0.7 on 2020-07-29 13:00

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_create_tree_node_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="MineralType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trivial_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="trivial name"
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="variety"
                    ),
                ),
                (
                    "minerals",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="minerals"
                    ),
                ),
                (
                    "mohs_scale",
                    django.contrib.postgres.fields.ranges.DecimalRangeField(
                        blank=True, null=True
                    ),
                ),
                (
                    "density",
                    django.contrib.postgres.fields.ranges.DecimalRangeField(
                        blank=True, null=True
                    ),
                ),
                ("streak", models.CharField(max_length=100, verbose_name="streak")),
                (
                    "normal_color",
                    models.CharField(max_length=100, verbose_name="normal color"),
                ),
                (
                    "fracture",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("CF", "conchoidal"),
                                ("EF", "earthy"),
                                ("HF", "hackly"),
                                ("SF", "splintery"),
                                ("UF", "uneven"),
                            ],
                            max_length=2,
                        ),
                        null=True,
                        size=None,
                        verbose_name="fracture",
                    ),
                ),
                (
                    "lustre",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("AM", "adamantine lustre"),
                                ("DL", "dull lustre"),
                                ("GR", "greasy lustre"),
                                ("MT", "metallic lustre"),
                                ("PY", "pearly lustre"),
                                ("SL", "silky lustre"),
                                ("SM", "submetallic lustre"),
                                ("VT", "vitreous lustre"),
                                ("WY", "waxy lustre"),
                            ],
                            max_length=2,
                        ),
                        null=True,
                        size=None,
                        verbose_name="lustre",
                    ),
                ),
                (
                    "chemical_formula",
                    models.CharField(max_length=100, verbose_name="chemical formula"),
                ),
                (
                    "other",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="comment"
                    ),
                ),
                (
                    "resource_mindat",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MinDat ID"
                    ),
                ),
                (
                    "resource_mineralienatlas",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MineralienAtlas ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="last modified"),
                ),
                (
                    "systematics",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profiles",
                        to="content.TreeNode",
                        verbose_name="Steckbrief-Ebene",
                    ),
                ),
            ],
            options={
                "verbose_name": "mineral type",
                "verbose_name_plural": "mineral types",
            },
        ),
    ]
