# Generated by Django 3.0.7 on 2021-02-26 09:31

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_treenode_name_attributes'),
        ('geomat_content', '0003_crystalsystem_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltype',
            name='tree_node',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles', related_query_name='profile', to='content.TreeNode'),
        ),
    ]
