# Generated by Django 3.0.7 on 2021-02-26 09:42

from django.db import migrations

# Generated by Django 3.0.8 on 2021-02-16 16:06

from django.db import migrations


def populate_tree_node_with_systematics(apps, schema_editor):
    """
    Populate tree_node fields with systematics values.
    """
    MineralType = apps.get_model("geomat_content", "MineralType")

    for obj in MineralType.objects.all():
        obj.tree_node = obj.systematics
        obj.save()


def populate_systematics_with_tree_node(apps, schema_editor):
    """
    Populate systematics fields with tree_node values.
    """
    MineralType = apps.get_model("geomat_content", "MineralType")

    for obj in MineralType.objects.all():
        obj.systematics = obj.tree_node
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("geomat_content", "0004_auto_20210226_1031"),
    ]

    operations = [
        migrations.RunPython(
            populate_tree_node_with_systematics, populate_systematics_with_tree_node
        ),
    ]
