# Generated by Django 3.0.7 on 2021-02-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0005_auto_20210226_1042'),
    ]

    operations = [
        migrations.RemoveField(model_name="mineraltype", name="systematics", ),
    ]
