# Generated by Django 3.0.7 on 2021-04-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0006_auto_20210226_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineraltype',
            old_name='minerals',
            new_name='name',
        ),
    ]
