# Generated by Django 3.0.7 on 2021-10-10 15:57

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0007_auto_20210422_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True)),
                ('fracture', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CF', 'conchoidal'), ('EF', 'earthy'), ('HF', 'hackly'), ('SF', 'splintery'), ('UF', 'uneven')], max_length=2), null=True, size=None, verbose_name='fracture')),
                ('lustre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AM', 'adamantine lustre'), ('DL', 'dull lustre'), ('GR', 'greasy lustre'), ('MT', 'metallic lustre'), ('PY', 'pearly lustre'), ('SL', 'silky lustre'), ('SM', 'submetallic lustre'), ('VT', 'vitreous lustre'), ('WY', 'waxy lustre')], max_length=2), null=True, size=None, verbose_name='lustre')),
                ('mohs_scale', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True)),
                ('streak', models.CharField(max_length=100, verbose_name='streak')),
                ('normal_color', models.CharField(max_length=100, verbose_name='normal color')),
                ('mineral_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='geomat_content.MineralType', verbose_name='mineral type')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.TextField(blank=True, max_length=500, verbose_name='comment')),
                ('resource_mindat', models.CharField(blank=True, max_length=100, verbose_name='MinDat ID')),
                ('resource_mineralienatlas', models.CharField(blank=True, max_length=100, verbose_name='MineralienAtlas ID')),
                ('mineral_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='miscellaneous', to='geomat_content.MineralType', verbose_name='mineral type')),
            ],
        ),
        migrations.AddField(
            model_name='cleavage',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleavage', to='geomat_content.Property', verbose_name='mineral type'),
        ),
    ]
