# Generated by Django 3.0.7 on 2021-09-06 16:09

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0007_auto_20210422_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineraltype',
            name='density',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='mineraltype',
            name='mohs_scale',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True, verbose_name='mohs scale'),
        ),
    ]
