# Generated by Django 3.0.7 on 2021-10-10 15:59

from django.db import migrations

def populate_new_model(apps, schema_editor):

    MineralType = apps.get_model("geomat_content", "MineralType")
    Miscellaneous = apps.get_model("geomat_content", "Miscellaneous")
    Property = apps.get_model("geomat_content", "Property")
    for obj in MineralType.objects.all():
        new_prop = Property.objects.create(
            density=obj.density,
            fracture=obj.fracture,
            lustre=obj.lustre,
            mohs_scale=obj.mohs_scale,
            streak=obj.streak,
            normal_color=obj.normal_color,
            mineral_type=obj,
        )
        for cleav in obj.cleavage.all():

            new_prop.cleavage.add(cleav)
            new_prop.save()

        new_misc = Miscellaneous.objects.create(
            other=obj.other,
            resource_mindat=obj.resource_mindat,
            resource_mineralienatlas=obj.resource_mineralienatlas,
            mineral_type=obj,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0008_miscellaneous_property'),
    ]

    operations = [
        migrations.RunPython(populate_new_model, reverse_code=migrations.RunPython.noop)
    ]
