# Generated by Django 3.0.7 on 2021-10-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0009_auto_20211010_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleavage',
            name='mineral_type',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='density',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='fracture',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='lustre',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='mohs_scale',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='normal_color',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='other',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='resource_mindat',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='resource_mineralienatlas',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='streak',
        ),
    ]
