# Generated by Django 3.0.7 on 2021-10-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0011_property_cleavage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='cleavage',
        ),
        migrations.DeleteModel(
            name='Cleavage',
        ),
    ]
