# Generated by Django 3.0.7 on 2021-10-18 14:45

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0014_migrate_to_mediaobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscellaneous',
            options={'verbose_name': 'Miscellaneous', 'verbose_name_plural': 'Miscellaneous'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='lustre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AM', 'adamantine lustre'), ('DL', 'dull lustre'), ('GR', 'greasy lustre'), ('MT', 'metallic lustre'), ('PY', 'pearly lustre'), ('SL', 'silky lustre'), ('SM', 'submetallic lustre'), ('VT', 'vitreous lustre'), ('WY', 'waxy lustre')], max_length=2, verbose_name='lustre'), null=True, size=None, verbose_name='lustre'),
        ),
        migrations.AlterField(
            model_name='property',
            name='mohs_scale',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True, verbose_name='mohs_scale'),
        ),
    ]
