# Generated by Django 3.0.7 on 2021-10-18 15:05

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0015_auto_20211018_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='density',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True, verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='property',
            name='mohs_scale',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True, verbose_name='mohs scale'),
        ),
    ]
