# Generated by Django 3.2.22 on 2023-10-30 15:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_treenode_name_attributes'),
        ('geomat_content', '0016_auto_20211018_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineraltype',
            name='tree_node',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mineraltype_related', related_query_name='mineraltypes', to='content.treenode'),
        ),
    ]
