# Generated by Django 3.2.22 on 2023-10-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0017_alter_mineraltype_tree_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='minerals')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='variety')),
                ('trivial_name', models.CharField(blank=True, max_length=100, verbose_name='trivial name')),
                ('chemical_formula', models.CharField(max_length=100, verbose_name='chemical formula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('mineral_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_information', to='geomat_content.mineraltype', verbose_name='mineral type')),
            ],
            options={
                'verbose_name': 'general information',
                'verbose_name_plural': 'general information',
            },
        ),
    ]
