# Generated by Django 3.2.22 on 2023-10-30 16:08

from django.db import migrations

def populate_general_information(apps, schema_editor):
    """
    Create and populate a model instance of GeneralInforamtion and link it to the
    respective plant.
    """
    MineralType = apps.get_model("geomat_content", "MineralType")
    GeneralInformation = apps.get_model("geomat_content", "GeneralInformation")

    for obj in MineralType.objects.all():
        GeneralInformation.objects.create(
            name=obj.name,
            variety=obj.variety,
            trivial_name=obj.trivial_name,
            chemical_formula=obj.chemical_formula,
            created_at=obj.created_at,
            last_modified=obj.last_modified,
            mineral_type=obj
        )

def populate_plant_fields(apps, schema_editor):
    """
    Populate the fields of a Plant model instance form the linked GeneralInformation
    model instance.
    """
    MineralType = apps.get_model("geomat_content", "MineralType")

    for obj in MineralType.objects.all():
        general_info = obj.general_information
        obj.name = general_info.name
        obj.variety = general_info.variety
        obj.trivial_name = general_info.trivial_name
        obj.chemical_formula = general_info.chemical_formula
        obj.created_at = general_info.created_at
        obj.last_modified = general_info.last_modified
        obj.save()
        general_info.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0018_generalinformation'),
    ]

    operations = [
        migrations.RunPython(
            populate_general_information, populate_plant_fields
        )
    ]
