# Generated by Django 3.2.22 on 2023-11-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0019_migrate_mineraltype_fields_to_generalinformationpy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineraltype',
            name='chemical_formula',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='trivial_name',
        ),
        migrations.RemoveField(
            model_name='mineraltype',
            name='variety',
        ),
    ]
