# Generated by Django 3.2.22 on 2023-11-02 12:57

from django.db import migrations
import solid_backend.utils.drf_spectacular_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0020_auto_20231102_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='chemical_formula',
            field=solid_backend.utils.drf_spectacular_extensions.MDTextField(max_length=100, verbose_name='chemical formula'),
        ),
    ]
