# Generated by Django 3.2.22 on 2024-01-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0021_alter_generalinformation_chemical_formula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='trivial_name',
            new_name='sub_name',
        ),
    ]
