# Generated by Django 3.2.22 on 2024-01-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomat_content', '0023_rename_variety_generalinformation_variety_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='sub_name',
            new_name='trivial_name',
        ),
    ]
